import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-[100vh] bg-[#000] w-screen overflow-hidden">
        {children}
        </body>
    </html>
  );
}
